[package]
name = "serde_learn"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = {version = "1.0.225", features = ["derive"]}
serde_json = {version = "1.0.145"}

[dev-dependencies]
cargo-husky = {version = "1.5.0"}
